# This file was generated by GoReleaser. DO NOT EDIT.
cask "harnest" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "f509f01c4de0a8b174027c55106b4a2d77d02b701eea2782ff8948bc1b20d9c8"
      url "https://github.com/nishimoto265/harnest/releases/download/v#{version}/harnest_darwin_amd64"
      binary "harnest_darwin_amd64", target: "harnest"
    end
    on_arm do
      sha256 "3a837b34bf54f4826fecc478de505f7a2e6a754d55fa7ba8206a7d26d4ed9580"
      url "https://github.com/nishimoto265/harnest/releases/download/v#{version}/harnest_darwin_arm64"
      binary "harnest_darwin_arm64", target: "harnest"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d5d8f125f3e02f6dda5f4f881695db5c49da79cfbf8a1a30e819cc7b33c3797"
      url "https://github.com/nishimoto265/harnest/releases/download/v#{version}/harnest_linux_amd64"
      binary "harnest_linux_amd64", target: "harnest"
    end
  end

  name "harnest"
  desc "Self-improving harness pipeline for AI coding agents"
  homepage "https://github.com/nishimoto265/harnest"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

  caveats <<~EOS
    HarNest depends on git, gh, jq, yq, lsof, and configured Codex/Claude CLIs.
    Run `harnest preflight` before enabling scheduled runs.
  EOS
end
