# This file was generated by GoReleaser. DO NOT EDIT.
cask "harnest" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "cd6bc901442a0a379b26287faf8bdd9bfb088158d8489e49c4d3ba0826669483"
      url "https://github.com/nishimoto265/auto-improve/releases/download/v#{version}/harnest_darwin_amd64"
      binary "harnest_darwin_amd64", target: "harnest"
    end
    on_arm do
      sha256 "91f0358776ca1beae4c1ac66937a93209c23880866d6a5364931670e74a0a7fd"
      url "https://github.com/nishimoto265/auto-improve/releases/download/v#{version}/harnest_darwin_arm64"
      binary "harnest_darwin_arm64", target: "harnest"
    end
  end

  on_linux do
    on_intel do
      sha256 "96a555ebf4f99b8c77324a73bdedbaa77c2800be2ffb4d9abade29a3cadf7b51"
      url "https://github.com/nishimoto265/auto-improve/releases/download/v#{version}/harnest_linux_amd64"
      binary "harnest_linux_amd64", target: "harnest"
    end
  end

  name "harnest"
  desc "Self-improving harness pipeline for AI coding agents"
  homepage "https://github.com/nishimoto265/auto-improve"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

  caveats <<~EOS
    HarNest depends on git, gh, jq, yq, lsof, and configured Codex/Claude CLIs.
    Run `harnest preflight` before enabling scheduled runs.
  EOS
end
